chore: error refinement improvements decrypt/encrypt strategy
aws/aws-cryptographic-material-providers-library pull request #1061
Opened 2024-11-27 01:07 UTC by josecorella

_Issue #, if available:_

_Description of changes:_

_Squash/merge commit message, if applicable:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-27 01:31 UTC, texastony requested changes

2024-11-27 01:31 UTC, texastony commented on AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy
> +          }
Blocking/Suggestion: a Mutation using Encyrpt is MutationToException.
```suggestion
          if (hasEncrypt?.Some?) {
            return Types.MutationToException(
                message := "Key Management denied access based on the terminal properties."
                + " Mutation is halted. Check encrypt access to KMS ARN: " + terminalKmsArn + "."
                + "\n" + errorContext
              );
          }
```

2024-11-27 01:31 UTC, texastony commented on AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationExampleDecryptEncryptStrategy.java
> +    );
Suggestion: we should add a clean up call,
so that our test table does not continue to grow in size.

2024-11-27 01:31 UTC, texastony commented on AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java
> +      );
Suggestion: We can refactor the Mutation Resume Example to take in a strategy.

2024-11-27 05:23 UTC, josecorella commented on AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationExampleDecryptEncryptStrategy.java
> +    terminalEC.put("Koda", "is a dog.");
nice

2024-11-27 05:24 UTC, josecorella reviewed
sad I can't approve my own pr

2024-11-27 06:04 UTC, texastony approved these changes

2024-11-27 23:07 UTC, texastony approved these changes
We can ship this for today and address the fall though case tomorrow.

2024-11-27 23:07 UTC, texastony commented on AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy
> +            );
This is wrong.
I should have caught this earlier.
This case WILL happen if the two booleans fire but no match occurs,
which is a possibility.
In which case, we should fall through to the final return on 176.

2024-11-27 23:09 UTC, merged

2024-11-30 19:40 UTC, texastony commented on AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy
> +            );
I was wrong (again) when I wrote this comment.
This should be impossible, as the operation matched.