fix(.NET): Improve Collection of Errors string
aws/aws-cryptographic-material-providers-library pull request #1158
Opened 2024-12-23 22:17 UTC by texastony

_Issue #, if available:_

Collection of Errors is a frustrating error because it requires customer action
to completely serialize it into logs.

We can make a simple fix in .NET to improve the CX,
by always serializing the list into the Collection Of Error's
message.

We concatenate the given error message with
a serialization of all the nested errors.

See similar PR for MPL-Java: https://github.com/aws/aws-cryptographic-material-providers-library/commit/9e195a1960fa18e1dc6efd0c9057c2ec6aed8e11

*Squash/merge commit message, if applicable:*
```
fix(.NET): Improve Collection of Errors string 
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2025-01-02 19:40 UTC, rishav-karanjit submitted a review, later dismissed
~Looks good to me~

Got 2 new comments

2025-01-02 19:43 UTC, rishav-karanjit reviewed
Are we skipping https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/KeyVectors/CollectionOfErrors.cs because its a test?

2025-01-02 19:59 UTC, rishav-karanjit requested changes

2025-01-02 19:59 UTC, rishav-karanjit commented on AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/CollectionOfErrors.cs
> +    private static string ListAsString(List<Exception> list)
We are not importing System.Collections.Generic.List
```suggestion
    private static string ListAsString(System.Collections.Generic.List<Exception> list)
```
Here and other places

2025-01-03 17:43 UTC, texastony commented
> Are we skipping https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/KeyVectors/CollectionOfErrors.cs because its a test?

Yes. There is no customer impact, so I am not inclined to increase our Beneration scope.

2025-01-03 17:43 UTC, texastony commented on AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/CollectionOfErrors.cs
> +    private static string ListAsString(List<Exception> list)
See https://github.com/aws/aws-encryption-sdk-dafny/pull/728#discussion_r1902016907

2025-01-03 18:06 UTC, rishav-karanjit commented on AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/CollectionOfErrors.cs
> +    private static string ListAsString(List<Exception> list)
We are missing a import here. Thats why its a blocking comment.

For example: when I try to run this (below) it work but if I remove `using System.Collections.Generic` it will give me an error.
```
using System;
using System.Collections.Generic;

public class HelloWorld
{
    public static void Main(string[] args)
    {
        // Create a new List of strings
        List<string> names = new List<string>();

        // Add items to the list
        names.Add("Alice");
        names.Add("Bob");
        names.Add("Charlie");

        // Print all items in the list
        Console.WriteLine("All names:");
        foreach (string name in names)
        {
            Console.WriteLine(name);
        }
    }
}
```

2025-01-03 18:17 UTC, texastony commented on AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/CollectionOfErrors.cs
> +    private static string ListAsString(List<Exception> list)
Yes, you nailed it. 
I got it to work for one of the three PRs, and did not verify across all three repos.

Great catch.

2025-03-18 19:20 UTC, closed without merging